#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Image

# import RPi.GPIO as GPIO
from raspi_motor_driver.srv import *


class CommandsProto(object):
    def __init__(self):
        rospy.init_node('commands_proto')

        self.sub1 = rospy.Subscriber('/motor_control/command', MoveCommand, self.dummy_handler)

        rospy.spin()

    @staticmethod
    def dummy_handler(command):
        rospy.logdebug("received command: {0}".format(command.direction))

    @staticmethod
    def emergency_stop(image):
        """ This does not work in real life """
        if all(value == image.data[0] for value in image.data):
            """ Uniform image ahead -> Stop"""
            rospy.logwarn("stopping!!!")
        else:
            rospy.loginfo("all is well")


if __name__ == '__main__':
    try:
        CommandsProto()

    except rospy.ROSInterruptException:
        # GPIO.cleanup()
        pass